version: '3.0'
 
services:
   db:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: myappdb
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always
 
   myapp:
     depends_on:
       - db
 #    image: amanganiello90/dotnet-app
     build:
       context: .
     ports:
       - "5000:80"
 
volumes:
    dbdata: